/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type NewEventEmitter = ContractEventLog<{
  contractAddress: string;
  0: string;
}>;

export interface CrossContractReader extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): CrossContractReader;
  clone(): CrossContractReader;
  methods: {
    deploy(): NonPayableTransactionObject<void>;

    deployRemote(crossAddress: string): NonPayableTransactionObject<void>;

    destroy(): NonPayableTransactionObject<void>;

    increment(): NonPayableTransactionObject<void>;

    incrementRemote(crossAddress: string): NonPayableTransactionObject<void>;

    read(emitter_address: string): NonPayableTransactionObject<string>;

    remoteDestroy(crossAddress: string): NonPayableTransactionObject<void>;
  };
  events: {
    NewEventEmitter(cb?: Callback<NewEventEmitter>): EventEmitter;
    NewEventEmitter(
      options?: EventOptions,
      cb?: Callback<NewEventEmitter>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "NewEventEmitter", cb: Callback<NewEventEmitter>): void;
  once(
    event: "NewEventEmitter",
    options: EventOptions,
    cb: Callback<NewEventEmitter>
  ): void;
}
